### ISSUE TITLE
[Datapicker] Calendar is not correct.

### ISSUE THREAD

**Issue by OuyangQianba** [mlaursen/react-md#653] opened 2017-12-22 04:37 UTC
### Description

It seems calendar is not correct. please see the below pictures.

### Images/Screenshots

![image](https://user-images.githubusercontent.com/17270099/34285351-2914cdce-e714-11e7-9eaa-cdc3ad4893dc.png)

![image](https://user-images.githubusercontent.com/17270099/34285356-2f710200-e714-11e7-9e48-cc803dd20bd5.png)

### Version
- React - （I don't know, I see this in your [website](
https://react-md.mlaursen.com/components/pickers/date)  )
- React-MD -（I don't know, I see this in your website )
- Browser

**Comment by hisapy** [comment] 2017-12-22 12:28
Please close this issue as is a duplicate of #634

**Closed** 2017-12-25 05:54 UTC
