### ISSUE TITLE
IconButton is clickable when disabled

### ISSUE THREAD

**Issue by GeorgeLolos** [mlaursen/react-md#158] opened 2016-11-18 15:32 UTC
If there's an onClick function on an IconButton, the button is clickable even when it's disabled.

The CSS styles are applied, so the IconButton is grayed out, but still clickable.

I believe the reason is that the onClick function is applied on the <i> element rather than the button.

**Comment by mlaursen** [comment] 2016-11-18 16:24
Could you give me the current `react-md` version this is happening in? It has been fixed in `v1.0.0` and depending on how old it is, I might not patch it.

**Comment by GeorgeLolos** [comment] 2016-11-21 08:41
I see. The version is 0.3.7

**Comment by mlaursen** [comment] 2016-11-21 12:42
Ok, that isn't far aback at all. I'll look into patching that for `v0.3.8`

**Comment by mlaursen** [comment] 2016-11-21 17:17
What version of React is this for as well? I am unable to reproduce this with the following examples:


```js
function handleClick(e) {
  console.log('Clicked!', e.target);
}

class Tests extends Component {
  _handleClick(e) {
    console.log('Clicked!', e.target);
  },

  render() {
    return (
      <div>
        <IconButton disabled onClick={handleClick}>favorite</IconButton>
        <IconButton disabled onClick={(e) => { console.log('Clicked!', e.target); }}>favorite</IconButton>
        <IconButton disabled onClick={this._handleClick}>favorite</IconButton>
      </div>
    );
  }
}
```

All of these tests did not print anything in the console when clicked.

However, I can reproduce if I pass an `href` to the `IconButton`. I can quickly fix the rendering the `IconButton` as a link part.

```js
const Test = () => (
  <IconButton href="#" disabled onClick={e => { console.log('Clicked!', e.target); }}>favorite</IconButton>
);

Is this happening for you as the default `IconButton`?

**Comment by GeorgeLolos** [comment] 2016-11-22 09:10
Ok so the React version is 15.4.0
There's no href on the button and I just noticed that on my first comment the markdown of github messed it up. What I tried to say is that the onClick event is bound to the " < i >" element rather than the button element

```

Clicked! <i class="md-icon material-icons">favorite</i>
Clicked! <i class="md-icon material-icons">favorite</i>
Clicked! <i class="md-icon material-icons">favorite</i>

```

**Comment by mlaursen** [comment] 2016-11-22 15:15
Ahh. There isn't actually much I can do about this actually. This is how the event pooling/bubbling (I forgot what the real term is) works. The click event is actually bound to the `button` element and not the `i`. It just depends on where the user clicks on the button.

[Video example](https://gfycat.com/DimwittedClumsyAfricanbushviper)

**Comment by mlaursen** [comment] 2016-11-23 21:05
You can always remove this behavior by adding the following css:

```scss
.md-btn * {
  pointer-events: none;
}
```

However, I do not think this should be a part of the base library since it is valid to check what child in the button is clicked.

**Closed by mlaursen** 2016-11-23 21:05 UTC
Labels: bug

**Comment by GeorgeLolos** [comment] 2016-11-24 15:45
Great, thanks a lot! Keep it up 😃
