### ISSUE TITLE
[TextField] - Warning raised when it is of type date

### ISSUE THREAD

**Issue by dferrazm** [mlaursen/react-md#476] opened 2017-08-10 08:57 UTC
A warning is raised when passing `type="date"` to use the TextField as a native HTML date input.

![screenshot from 2017-08-10 10-55-52](https://user-images.githubusercontent.com/526386/29162761-a6184d0a-7dba-11e7-8804-5fc93b0225eb.png)

I guess `date` could be included in the accepted types, right?

### Version
- React-MD - 1.0.18

**Comment by mlaursen** [comment] 2017-08-22 11:00
Marking this a duplicate of #486 even though this was made after (I saw the other one first).

Explanation is [here](https://github.com/mlaursen/react-md/issues/486#issuecomment-323671812).

**Closed by mlaursen** 2017-08-22 11:00 UTC
Labels: duplicate
