### ISSUE TITLE
[DialogContainer] Nested dialogs = layout bug

### ISSUE THREAD

**Issue by ostrebler** [mlaursen/react-md#635] opened 2017-11-21 15:38 UTC
### Description
When trying to open a dialog in another dialog, both dialogs jump at the top of the screen and are barely visible.

### Images/Screenshots
Before opening the second dialog :
![dialog](https://user-images.githubusercontent.com/30187797/33081294-4caa524c-ceda-11e7-94b3-9806e55f926d.png)
After :
![dialog2](https://user-images.githubusercontent.com/30187797/33081295-4cc30b8e-ceda-11e7-8094-56b8beda3d05.png)

### Version
- React - latest
- React-MD - latest

**Comment by DaVinciLord** [comment] 2017-11-22 10:59
I think this is th same issue as #595. 
Basically, use the [disableScrollLocking](https://react-md.mlaursen.com/components/dialogs?tab=1#dialog-container-proptypes-disable-scroll-locking) prop in the child dialog if I'm correct and everything should be fine.

**Comment by mlaursen** [comment] 2017-11-22 16:25
Yeah, this looks like a duplicate of #595. I'll add an example of nested dialogs to the documentation site that might help showcase this bug and fix.

**Comment by ostrebler** [comment] 2017-11-22 16:53
Mmmh not really. I mean, yes, disableScrollLocking prevents from jumping to the top, but it doesn't actually create a new overlay. That is problematic in my case where I would expect only the second dialog to close when clicking one time outside the zone. Moreover, the second dialog is "fit" in the first one. In my case, the second is higher than the first. I would like to show the nested dialog above everything else, including the first one as if it didn't exist. Any way to do that ?

**Comment by mlaursen** [comment] 2017-11-22 17:38
Yeah, it isn't the best solution though. Your inner dialogs should have `portal`, `disableScrollLocking`, and `lastChild` enabled as well as setting the `renderNode={document.body}`

See this [codepen](https://codepen.io/mlaursen03/pen/gXzLZv?editors=0010) for a working example. I might be able to simplify it a bit and remove some of the pre-1.1.0 portal fixes that will make it so you don't need to do `renderNode={document.body}`.

I'll add some more notes later about *why* this works when I get some time.

**Comment by ostrebler** [comment] 2017-11-22 17:53
Aaaaaand it works perfectly ! Thank you.

**Closed** 2017-11-22 17:54 UTC
Labels: duplicate

**Comment by ostrebler** [comment] 2017-11-22 17:57
I don't know what are your motivations to remove renderNode, but I helped a lot in my case. My CSS styles are applied according to the #id of a child node of document.body. In my case, I used : 
```
renderNode={ $('#workspace-content')[0] }
```

**Comment by mlaursen** [comment] 2017-11-22 18:24
Here's an explanation about **why** it works and **why** each of these props need to be added.

Due to each browser calculating view height and view-width differently, the dialog's size is based on fixing the dialog to a parent element (`max-height: calc(100% - $padding); max-width: calc(100% - $padding);`). In most cases this will be the full window size and work as expected, however some browsers treat `position: fixed` as a new relative container for nested \`position: fixed\` elements. This means that a nested dialog would have a max height and width of the parent dialog instead of the full page size.

To get around this, we enable the `portal` prop and set the `renderNode` to the `document.body` or some other element so that it is now setting size based on window size. The only reason the `renderNode` needs to be set right now is that some logic pre-1.1.0 was created so that `renderNode`s are set to parent dialogs or parent drawers to help with nested portals. It'll probably be better from now on only to set the `renderNode` automatically if it is in a full page dialog instead so it will have correct z-indexing.

The next problem is now that we portal-ed the inner dialogs out, they will appear underneath the parent dialogs since they were rendered as the first element which has a lower z-index by default. Enabling `lastChild` now makes it have the highest z-index and will appear over the parent dialog.

Hopefully that wasn't too confusing.

**Comment by ostrebler** [comment] 2017-11-22 18:28
That's very clear, thank you for the explanation.
