### ISSUE TITLE
react lifecycle warnings

### ISSUE THREAD

**Issue by devs9** [mlaursen/react-md#848] opened 2019-08-29 13:45 UTC
Please, pay attention to the components that use outdated methods for react life cycle.

for detailed information: https://fb.me/react-async-component-lifecycle-hooks

I got these warnings:
<img width="1675" alt="Снимок экрана 2019-08-29 в 16 31 49" src="https://user-images.githubusercontent.com/45544661/63945612-4beba280-ca7c-11e9-89ee-077590812c12.png">

**Comment by mlaursen** [comment] 2019-08-29 16:23
Unfortunately I don't think I'll be able to do this in the v1 release since using the `react-codemod` does not fix it completely due to some other dependencies. Upgrading the dependencies will force me to re-write some of the components since the API have changed so I'd much rather have this automatically fixed with the v2 rewrite.

I would be happy if you'd like to take a stab at it, but I'll be holding off until the v2 release. Sorry :(

**Comment by GO-gyan** [comment] 2019-08-30 07:04
> Unfortunately I don't think I'll be able to do this in the v1 release since using the `react-codemod` does not fix it completely due to some other dependencies. Upgrading the dependencies will force me to re-write some of the components since the API have changed so I'd much rather have this automatically fixed with the v2 rewrite.
> 
> I would be happy if you'd like to take a stab at it, but I'll be holding off until the v2 release. Sorry :(

When can we expect v2 release.

**Comment by devs9** [comment] 2019-08-31 02:01
Of course, it’s better to re write on these methods, but i thinking,
you can simply rename it and not change the logic of the components ... The warnings show that the problems are only with UNSAFE methods.

And what do you mean about api changed?

**Comment by mlaursen** [comment] 2019-08-31 15:14
Hey sorry. I might've given up too soon for this so let me take another try at it. I had run the react-codemod to rename all the old lifecycles to be prefixed with `UNSAFE_` and updated dev dependencies for react, react-dom, and the testing libraries but this caused the majority of my tests to fail. I'll see if I can at least get this part to work before v2.

The dependency that had breaking API changes and still throws the deprecated lifecycle warnings in react-transition-group since I'm still using the old v1.0.2 for it here. The new API is fantastic (using it in v2) but requires some decent changes since the components and triggering animations changes quite a bit.

I really gave up quickly on this so I could try to continue focusing on v2 since it's taking much longer than I had hoped to release. It would be fantastic if someone from the community could pick this up to fix (from my standpoint), but that isn't really really fair for the users of this library since my v1 branch is hard to contribute to now since it hasn't been fully maintained to work with node > 8

**Comment by zachsa** [comment] 2019-09-04 11:01
I've also noticed the warnings. however they are just warnings and they won't kill you. There's a related issue on the React source code for this: https://github.com/JedWatson/react-select/issues/3715

Thanks very much for an amazing library of components, and looking forward to trying V2 when it comes out!

**Comment by misolo** [comment] 2020-04-21 18:51
Is there a way to disable/ignore/delete these warnings? It makes my console "dirty" and I always think they were caused by my code ...

**Comment by mlaursen** [comment] 2020-05-06 23:37
Unfortunately I think the only way this can be done right now is to pin `react` and `react-dom` at `16.8.3` which is the last available version before they added these warnings :/ If this is not a valid solution, you can always try to filter out these console warnings with the dev tools or override the default console warning in tests.

But maybe some good news. I've updated the v2 status thread with the last few things required for the v2 release: [#826](https://github.com/mlaursen/react-md/issues/826#issuecomment-624421065). It's really close.

**Closed** 2020-06-15 00:38 UTC
Labels: bug

**Comment by chandawarlokesh** [comment] 2022-03-16 09:09
Do we have the same fix for react-select version 1.3.0 as I can't upgrade react-select in my project due to some reasons, but want to remove such warnings?

My pacakge.json includes
react: 16.14.0,
react-dom: 15.14.0,
react-select: 1.3.0,

TIA
