### ISSUE TITLE
Disabling DialogFooter in ExpansionPanel

### ISSUE THREAD

**Issue by asoluter** [mlaursen/react-md#343] opened 2017-04-21 08:56 UTC
### Description
It would be perfect to add property to ExpansionPanel, which will enable/disable rendering DialogFooter in ExpansionPanel, as it's not always applicable.
### Version
- React-MD v1.0.11

**Comment by mlaursen** [comment] 2017-04-22 18:20
I think this is a duplicate of #306. Closing in favor of that one.

**Closed by mlaursen** 2017-04-22 18:20 UTC
Labels: duplicate
