### ISSUE TITLE
A disabled button doesn't have focus by tabulation.

### ISSUE THREAD

**Issue by daturon** [mlaursen/react-md#411] opened 2017-06-15 11:02 UTC
When I use disabled param (disabled={ false }) for Button then I can't set focus on it by Tab.

**Comment by mlaursen** [comment] 2017-06-19 22:29
If the `disabled` prop is enabled, the button *should* not be tab-focusable just like the native `button`. I have been unable to reproduce it being untabbable if `disabled={false}` is provided to the button. Do you have an example for that?

**Comment by mlaursen** [comment] 2017-07-14 15:15
I am going to close this since this is desired behavior.

**Closed by mlaursen** 2017-07-14 15:15 UTC
Labels: wontfix
